In [12]:
# import the libraries I need

import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

# read the csv file and save it in a variable called df

df = pd.read_csv("diabetes.csv")

In [13]:
# print first 5 rows

df.head()

# check number of rows and columns

print(df.shape)

(768, 9)

In [14]:
# check data types and if there are missing values

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [15]:
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [16]:
# columns that should never actually be zero

cols_with_fake_zeros = ["Glucose","BloodPressure","SkinThickness","Insulin","BMI"]

# loop through each column and count how many zeros it has

for col in cols_with_fake_zeros:
    zero_count = (df[col] == 0).sum()
    print(col,"->",zero_count,"zeros")

Glucose -> 5 zeros
BloodPressure -> 35 zeros
SkinThickness -> 227 zeros
Insulin -> 374 zeros
BMI -> 11 zeros

df["Insulin_was_missing"] =

In [17]:
# create indicator columns before modifying any values

df["Insulin_was_missing"] = (df["Insulin"] == 0).astype(int)
df["SkinThickness_was_missing"] = (df["SkinThickness"] == 0).astype(int)

In [18]:
# impute zeros with group-wise median based on Outcome

df["Insulin"] = df.groupby("Outcome")["Insulin"].transform(
    lambda x: x.replace(0,x[x != 0].median())
)

In [19]:
# same imputation logic applied to SkinThickness

df["SkinThickness"] = df.groupby("Outcome")["SkinThickness"].transform(
     lambda x: x.replace(0,x[x != 0].median())
)

In [22]:
# only a small % of zeros in theses 3 columns, so simple median is enough

cols_to_fix = ["Glucose", "BloodPressure", "BMI"]

for col in cols_to_fix:
    median_value = df[col][df[col] !=0].median()
    df[col] = df[col].replace(0, median_value)
# check again to make sure no zeros left in these columns

df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome,Insulin_was_missing,SkinThickness_was_missing
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,121.656250,72.386719,29.089844,141.753906,32.455208,0.471876,33.240885,0.348958,0.486979,0.295573
std,3.369578,30.438286,12.096642,8.890820,89.100847,6.875177,0.331329,11.760232,0.476951,0.500156,0.456597
min,0.000000,44.000000,24.000000,7.000000,14.000000,18.200000,0.078000,21.000000,0.000000,0.000000,0.000000
25%,1.000000,99.750000,64.000000,25.000000,102.500000,27.500000,0.243750,24.000000,0.000000,0.000000,0.000000
50%,3.000000,117.000000,72.000000,28.000000,102.500000,32.300000,0.372500,29.000000,0.000000,0.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,169.500000,36.600000,0.626250,41.000000,1.000000,1.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000,1.000000,1.000000